### ISSUE TITLE
Stopped converting currencies

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#221] opened 2015-04-16 17:46 UTC
```
Chromium Version 39.0.2171.65 Built on Ubuntu 14.04, running on LinuxMint 17 
(64-bit)
```

Original issue reported on code.google.com by `denise...@hotmail.com` on 19 Jan 2015 at 1:37

**Comment by IIsi50MHz** [comment] 2015-04-20 05:57
Duplicate of issue #216

**Closed by IIsi50MHz** 2015-04-20 05:57 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
