### ISSUE TITLE
The temperature conversion (-20C in F) doesn't work for negative starting values

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#206] opened 2015-04-16 17:46 UTC
```
What steps will reproduce the problem?

What is the expected output?

What do you see instead?

What version of Chrome are you using?

What operating system are you using?

What country are you in?

Please provide any additional information below.

```

Original issue reported on code.google.com by `crui...@gmail.com` on 7 Jan 2014 at 8:07

**Comment by IIsi50MHz** [comment] 2015-04-20 05:40
Duplicate of issue #205

**Closed by IIsi50MHz** 2015-04-20 05:41 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
