### ISSUE TITLE
dot & comma using

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#201] opened 2015-04-16 17:46 UTC
```
Please add to settings ckeckbox for using comma(,) separator equals dot(.)
example:
0.25*1000 = 250
0,25*1000 = 25000

need to be able:
0.25*1000 = 250
0,25*1000 = 250

p.s. Very good extension! 
```

Original issue reported on code.google.com by `Shal1928@gmail.com` on 5 Nov 2013 at 5:56

**Comment by IIsi50MHz** [comment] 2015-04-20 05:34
Duplicate of issue #82

**Closed by IIsi50MHz** 2015-04-20 05:34 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
