### ISSUE TITLE
expressions not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#224] opened 2015-04-16 17:46 UTC
```
What steps will reproduce the problem?
For over few months now the expressions that used to work perfectly well before 
no longer do so. For example entering 100 usd in eur returns no answer. 

What is the expected output?
It is supposed to give me the respective value of a 100 USD in todays EUR/USD 
rate 

What do you see instead?
nothing. blank line

What version of Chrome are you using?
latest (40.0.2xxxx)

What operating system are you using?
Windows 8.1

What country are you in?
Bulgaria

Please provide any additional information below.

```

Original issue reported on code.google.com by `emil.gyo...@gmail.com` on 9 Mar 2015 at 8:24

**Comment by IIsi50MHz** [comment] 2015-04-20 06:04
Possible duplicate of issue #216

**Closed by IIsi50MHz** 2015-04-20 06:04 UTC
Labels: auto-migrated, bug, Component-Logic, duplicate, Priority-Medium, Usability
