### ISSUE TITLE
Currency conversions stopped working again

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#218] opened 2015-04-16 17:46 UTC
```
What steps will reproduce the problem?
Attempt to do a currency conversion in the calculator e.g. 300,000 INR in CHF

What is the expected output?
The amount in CHF

What do you see instead?
Nothing processes, the only item seen is the last calculation

What version of Chrome are you using?
Version 39.0.2171.95 (64-bit) 

What operating system are you using?
Mac OSX 10.9.5

What country are you in?
Switzerland

Please provide any additional information below.
This happened before but the previous time it attempted to execute the 
conversion and failed. Not sure if Google changed something but the currency 
conversions are consistently not working.

```

Original issue reported on code.google.com by `nfo...@google.com` on 17 Dec 2014 at 1:39

**Comment by IIsi50MHz** [comment] 2015-04-20 05:57
Duplicate of issue #216

**Closed by IIsi50MHz** 2015-04-20 05:57 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
