### ISSUE TITLE
International decimal point

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#153] opened 2015-04-16 17:46 UTC
```
US vs European decimal points:

10000 in US: 10,000
10000 in Europe: 10.000

55/10 in US: 5.5
55/10 in Europe: 5,5

Please be advised that when using European decimal points, cloudy calculator 
yields wrong results, ie:

100-5.5=94.5
100-5,5=45

It would be great if you could let the standard for decimal points follow the 
browser localization or similar.

Thanks


```

Original issue reported on code.google.com by `finn.kri...@jdrf.dk` on 19 Jul 2012 at 6:20

**Comment by IIsi50MHz** [comment] 2015-04-20 04:43
Duplicate of issue #82

**Closed by IIsi50MHz** 2015-04-20 04:43 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
