### ISSUE TITLE
can't toggle behaviour where, when the first term is a negative number, calculator automatically puts an @ symbol in front and subtracts the value from the previous result

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#178] opened 2015-04-16 17:46 UTC
```
What steps will reproduce the problem?
just type a negative number and press return, e.g. -50

What is the expected output?
-50

What do you see instead?
(whatever the previously calculated value was minus 50.

What version of Chrome are you using?
 24.0.1312.57 m
What operating system are you using?
windows 7

What country are you in?
switzerland

Please provide any additional information below.
```

Original issue reported on code.google.com by `cpiscite...@gmail.com` on 4 Feb 2013 at 3:13

**Comment by IIsi50MHz** [comment] 2015-04-20 05:09
Duplicate of issue #126

**Closed by IIsi50MHz** 2015-04-20 05:09 UTC
Labels: auto-migrated, Priority-Medium
