### ISSUE TITLE
part of window sometimes doesn't appear

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#209] opened 2015-04-16 17:46 UTC
```
What steps will reproduce the problem? Not sure

What is the expected output? The whole window

What do you see instead? Most of the window, missing the right-hand side 
(including the button to pop out the calculator)

What version of Chrome are you using?34.0.1847.131 m

What operating system are you using? Windows 8

What country are you in? US

Please provide any additional information below.

Sometimes I open up the calculator and the part of the window where the buttons 
(including the one to pop it out) doesn't appear. The only solution I've found 
so far is to remove the calculator and re-install it.

```

Original issue reported on code.google.com by `ron.sper...@gmail.com` on 30 Apr 2014 at 12:20

**Comment by IIsi50MHz** [comment] 2015-04-20 05:45
This can occur if you zoom in while viewing the extension's Options page. Duplicate of issue #95

**Closed by IIsi50MHz** 2015-04-20 05:45 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
