### ISSUE TITLE
Broken in new version of Chrome OS 0.12.433.57

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#114] opened 2015-04-16 17:45 UTC
```
What steps will reproduce the problem?
Extension "chromey-calculator" is installed with "chromey-calculator enhancer" 
on a Chrome OS device with the above version and an expression is entered to 
solve.

What is the expected output?
Pressing "enter" key will yield a solution for the expression entered.

What do you see instead?
Pressing "enter" key yields no change and expression still shows in input box.

What version of Chrome are you using?
12.0.742.68

What operating system are you using?
Chrome OS 0.12.433.57

What country are you in?
USA

Please provide any additional information below.
Changes to options menu (such as changes to text size and input window size) 
are not saved upon closing or refreshing the page.
```

Original issue reported on code.google.com by `vazlo...@gmail.com` on 29 May 2011 at 10:36

**Comment by IIsi50MHz** [comment] 2015-04-20 03:28
Possible duplicate of #100

**Closed by IIsi50MHz** 2015-04-20 03:28 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
