### ISSUE TITLE
cropped display on one computer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#105] opened 2015-04-16 17:45 UTC
```
What steps will reproduce the problem?
don't know 

What is the expected output?
full view of chromey-calculator drop down

What do you see instead?
cropped display of chromey-calculator which shows just the left side of the 
drop down (the "Clear | Options | Help | Popout icon" are not 
visible/available); see attached screen shot.

What version of Chrome are you using?
Version: 4.1.1.1

What operating system are you using?
windows 7 home premium 64bit (v6.1)

What country are you in?
usa

Please provide any additional information below.
works fine on 2nd computer and used to work fine on this computer. i've tried 
uninstalling extension, clearing chrome settings, restarting, re-installing, 
etc.

```

Original issue reported on code.google.com by `OliverGr...@gmail.com` on 6 Mar 2011 at 12:08

Attachments:
* [Capture.PNG](https://storage.googleapis.com/google-code-attachments/chromey-calculator/issue-105/comment-0/Capture.PNG)

**Comment by IIsi50MHz** [comment] 2015-04-20 02:23
Now thinking this is a likely duplicate of issue #95.

**Closed by IIsi50MHz** 2015-04-20 02:23 UTC
Labels: auto-migrated, Component-Logic, Component-UI, Priority-High, Type-Defect, Usability
