### ISSUE TITLE
Feature - custom popup shortcut

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#193] opened 2015-04-16 17:46 UTC
```
Please allow a custom keyboard shortcut - or at least use left alt. In my 
language right alt+c is used to enter a letter (ć)
```

Original issue reported on code.google.com by `ka...@o2.pl` on 22 Jul 2013 at 8:42

**Comment by IIsi50MHz** [comment] 2015-04-20 05:23
Duplicate of issue #51

**Closed by IIsi50MHz** 2015-04-20 05:23 UTC
Labels: auto-migrated, Priority-Low
